target-version = "py313"
line-length = 90
indent-width = 2
extend-exclude = [
  "chromio/filter/metadata/_antlr4",
]

[format]
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 90

[lint.flake8-quotes]
docstring-quotes = "double"
