name: Build and publish to PyPI

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version to publish (e.g., 1.2.3)
        required: true
        type: string

jobs:
  build:
    name: Build the package to publish
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Check package version
        shell: bash
        id: check_version
        run: |
          VERSION="${{ inputs.version}}"

          if ! grep -q "^version = \"$VERSION\"$" pyproject.toml; then
            echo "Error: Version $VERSION is not the same as this set in pyproject.toml"
            exit 1
          fi

      - name: Install Poetry
        run: pipx install poetry

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: poetry
      
      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Check pyproject.toml
        run: poetry check

      - name: Build the package
        run: poetry build

      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: package-dist
          path: dist/

  publish-to-testpypi:
    name: Publish to TestPyPI
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      id-token: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v6
        with:
          name: package-dist
          path: dist

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

  smoke-tests:
    name: Run the smoke tests
    runs-on: ubuntu-latest
    needs: [publish-to-testpypi]
    permissions:
      contents: read
    
    steps:
      - name: Install Chromie
        run: |
          pip install \
            --index-url https://test.pypi.org/simple/ \
            --extra-index-url https://pypi.org/simple/ \
            chromie-tool==${{ inputs.version }}
      
      - name: Run chromie smoke tests
        run: |
          which chromie
          chromie

  publish-to-pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [smoke-tests]
    permissions:
      id-token: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v6
        with:
          name: package-dist
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [publish-to-pypi]
    permissions:
      contents: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        
      - name: Download build artifacts
        uses: actions/download-artifact@v6
        with:
          name: package-dist
          path: dist
      
      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="v${{ inputs.version }}"
          gh release create $VERSION dist/* --title "Release $VERSION"
